"""add memory_history table for Rook

Revision ID: 4502328fd583
Revises: a1b2c3d4e5f6
Create Date: 2026-02-03 20:40:27.996067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4502328fd583'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intentions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_memory_id', sa.String(), nullable=True),
    sa.Column('trigger_conditions', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('fired', sa.Boolean(), nullable=True),
    sa.Column('fire_once', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('fired_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_intention_expires', 'intentions', ['expires_at'], unique=False)
    op.create_index('ix_intention_user_unfired', 'intentions', ['user_id', 'fired'], unique=False)
    op.create_index(op.f('ix_intentions_user_id'), 'intentions', ['user_id'], unique=False)
    op.create_table('memory_dynamics',
    sa.Column('memory_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('stability', sa.Float(), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('retrieval_strength', sa.Float(), nullable=True),
    sa.Column('storage_strength', sa.Float(), nullable=True),
    sa.Column('is_key', sa.Boolean(), nullable=True),
    sa.Column('importance_weight', sa.Float(), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('memory_id')
    )
    op.create_index('ix_memory_dynamics_user_accessed', 'memory_dynamics', ['user_id', 'last_accessed_at'], unique=False)
    op.create_index(op.f('ix_memory_dynamics_user_id'), 'memory_dynamics', ['user_id'], unique=False)
    op.create_table('memory_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('memory_id', sa.String(), nullable=False),
    sa.Column('old_memory', sa.Text(), nullable=True),
    sa.Column('new_memory', sa.Text(), nullable=True),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_history_memory_id'), 'memory_history', ['memory_id'], unique=False)
    op.create_index('ix_memory_history_memory_id_created', 'memory_history', ['memory_id', 'created_at'], unique=False)
    op.create_table('memory_supersessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('old_memory_id', sa.String(), nullable=False),
    sa.Column('new_memory_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_supersessions_new_memory_id'), 'memory_supersessions', ['new_memory_id'], unique=False)
    op.create_index(op.f('ix_memory_supersessions_old_memory_id'), 'memory_supersessions', ['old_memory_id'], unique=False)
    op.create_index(op.f('ix_memory_supersessions_user_id'), 'memory_supersessions', ['user_id'], unique=False)
    op.create_table('memory_access_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('memory_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('signal_type', sa.String(), nullable=True),
    sa.Column('retrievability_at_access', sa.Float(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('accessed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['memory_id'], ['memory_dynamics.memory_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_access_log_accessed_at'), 'memory_access_log', ['accessed_at'], unique=False)
    op.create_index(op.f('ix_memory_access_log_memory_id'), 'memory_access_log', ['memory_id'], unique=False)
    op.create_index(op.f('ix_memory_access_log_user_id'), 'memory_access_log', ['user_id'], unique=False)
    op.create_index('ix_memory_access_user_time', 'memory_access_log', ['user_id', 'accessed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_memory_access_user_time', table_name='memory_access_log')
    op.drop_index(op.f('ix_memory_access_log_user_id'), table_name='memory_access_log')
    op.drop_index(op.f('ix_memory_access_log_memory_id'), table_name='memory_access_log')
    op.drop_index(op.f('ix_memory_access_log_accessed_at'), table_name='memory_access_log')
    op.drop_table('memory_access_log')
    op.drop_index(op.f('ix_memory_supersessions_user_id'), table_name='memory_supersessions')
    op.drop_index(op.f('ix_memory_supersessions_old_memory_id'), table_name='memory_supersessions')
    op.drop_index(op.f('ix_memory_supersessions_new_memory_id'), table_name='memory_supersessions')
    op.drop_table('memory_supersessions')
    op.drop_index('ix_memory_history_memory_id_created', table_name='memory_history')
    op.drop_index(op.f('ix_memory_history_memory_id'), table_name='memory_history')
    op.drop_table('memory_history')
    op.drop_index(op.f('ix_memory_dynamics_user_id'), table_name='memory_dynamics')
    op.drop_index('ix_memory_dynamics_user_accessed', table_name='memory_dynamics')
    op.drop_table('memory_dynamics')
    op.drop_index(op.f('ix_intentions_user_id'), table_name='intentions')
    op.drop_index('ix_intention_user_unfired', table_name='intentions')
    op.drop_index('ix_intention_expires', table_name='intentions')
    op.drop_table('intentions')
    # ### end Alembic commands ###
