
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * List all notes, optionally filtered by folder
 */
async listNotes(folderId: number | null) : Promise<Result<Note[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_notes", { folderId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get a single note by ID
 */
async getNote(id: number) : Promise<Result<Note, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_note", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a new note
 */
async createNote(input: CreateNoteInput) : Promise<Result<Note, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_note", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update an existing note
 */
async updateNote(id: number, input: UpdateNoteInput) : Promise<Result<Note, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_note", { id, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a note
 */
async deleteNote(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_note", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all folders, optionally filtered by parent
 */
async listFolders(parentId: number | null) : Promise<Result<Folder[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_folders", { parentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get a single folder by ID
 */
async getFolder(id: number) : Promise<Result<Folder, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_folder", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a new folder
 */
async createFolder(input: CreateFolderInput) : Promise<Result<Folder, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_folder", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update an existing folder
 */
async updateFolder(id: number, input: UpdateFolderInput) : Promise<Result<Folder, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_folder", { id, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a folder (notes in folder will have folder_id set to NULL)
 */
async deleteFolder(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_folder", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Export a note to a markdown file at the specified path
 * Returns the path where the file was saved
 */
async exportNoteToFile(noteId: number, filePath: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_note_to_file", { noteId, filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get or create a daily note for a specific date.
 * Date format: YYYY-MM-DD (e.g., "2026-01-23")
 * If a daily note exists for that date, returns it.
 * If not, creates one with title "January 23, 2026" format.
 */
async getOrCreateDailyNote(date: string) : Promise<Result<Note, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_or_create_daily_note", { date }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all dates that have daily notes (for calendar highlighting)
 * Returns list of DailyNote with id, title, date, timestamps
 */
async listDailyNoteDates() : Promise<Result<DailyNote[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_daily_note_dates") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Search notes using FTS5 full-text search
 * Returns results ranked by BM25 with highlighted snippets
 */
async searchNotes(query: string, limit: number | null) : Promise<Result<SearchResult[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_notes", { query, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get all note titles for autocomplete
 * Returns notes ordered by most recently updated
 */
async getAllNoteTitles() : Promise<Result<NoteTitle[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_all_note_titles") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Extract wiki links from note content and save to wiki_links table
 * Returns the count of links saved
 */
async extractAndSaveWikiLinks(noteId: number, content: string) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("extract_and_save_wiki_links", { noteId, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get all notes that link TO the given note
 */
async getBacklinks(noteId: number) : Promise<Result<Backlink[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_backlinks", { noteId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get notes that mention this note's title without a wiki link wrapper
 */
async getUnlinkedMentions(noteId: number) : Promise<Result<UnlinkedMention[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_unlinked_mentions", { noteId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Backlink information for UI display
 */
export type Backlink = { id: number; title: string; updated_at: string }
/**
 * Input for creating a new folder
 */
export type CreateFolderInput = { name: string; parent_id: number | null }
/**
 * Input for creating a new note
 */
export type CreateNoteInput = { title: string; content: string | null; folder_id: number | null }
/**
 * A daily note entry (used for calendar display)
 */
export type DailyNote = { id: number; title: string; daily_note_date: string; created_at: string; updated_at: string }
/**
 * A folder for organizing notes
 */
export type Folder = { id: number; name: string; parent_id: number | null; created_at: string; updated_at: string }
/**
 * A note in the knowledge base
 */
export type Note = { id: number; title: string; content: string; folder_id: number | null; author: string; is_daily_note: boolean; daily_note_date: string | null; created_at: string; updated_at: string }
/**
 * A lightweight note title for autocomplete
 */
export type NoteTitle = { id: number; title: string }
/**
 * A search result with FTS5 ranking and snippet
 */
export type SearchResult = { id: number; title: string; snippet: string; rank: number }
/**
 * Unlinked mention information with snippet context
 */
export type UnlinkedMention = { id: number; title: string; snippet: string }
/**
 * Input for updating a folder
 */
export type UpdateFolderInput = { name: string | null; parent_id: number | null }
/**
 * Input for updating a note
 */
export type UpdateNoteInput = { title: string | null; content: string | null; folder_id: number | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
